import datetime                                                                                                                                                                                                                     
from typing import Optional                                                                                                                                                                                                         
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship                                                                                                                                                     
from sqlalchemy import String, Text, DateTime, Float, ForeignKey, Integer, Enum                                                                                                                                                     
import enum                                                                                                                                                                                                                         
                                                                                                                                                                                                                                    
class Base(DeclarativeBase):                                                                                                                                                                                                        
    pass                                                                                                                                                                                                                            
                                                                                                                                                                                                                                    
class ComplianceStatus(str, enum.Enum):                                                                                                                                                                                             
    HALAL = "HALAL"                                                                                                                                                                                                                 
    DOUBTFUL = "DOUBTFUL"                                                                                                                                                                                                           
    HARAM = "HARAM"                                                                                                                                                                                                                 
                                                                                                                                                                                                                                    
class User(Base):                                                                                                                                                                                                                   
    __tablename__ = "platform_users"                                                                                                                                                                                                
                                                                                                                                                                                                                                    
    id: Mapped[str] = mapped_column(primary_key=True)                                                                                                                                                                               
    username: Mapped[str] = mapped_column(String(50), unique=True, nullable=False)                                                                                                                                                  
    email: Mapped[Optional[str]] = mapped_column(String(120), nullable=True)                                                                                                                                                        
                                                                                                                                                                                                                                    
class Stock(Base):                                                                                                                                                                                                                  
    __tablename__ = "stocks"                                                                                                                                                                                                        
                                                                                                                                                                                                                                    
    ticker: Mapped[str] = mapped_column(String(10), primary_key=True)                                                                                                                                                               
    name: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)                                                                                                                                                         
    sector: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)                                                                                                                                                       
    industry: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)                                                                                                                                                     
    total_assets: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                                     
    total_debt: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                                       
    cash_equivalents: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                                 
    accounts_receivable: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                              
    total_revenue: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                                    
    interest_income: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                                  
    shares_outstanding: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                               
    avg_market_cap_36mo: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                              
    raw_info: Mapped[Optional[str]] = mapped_column(Text, nullable=True)                                                                                                                                                            
    sec_filing_url: Mapped[Optional[str]] = mapped_column(Text, nullable=True)                                                                                                                                                      
    fetched_at: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)                                                                                                                                                    
                                                                                                                                                                                                                                    
class AIOverride(Base):                                                                                                                                                                                                             
    __tablename__ = "ai_overrides"                                                                                                                                                                                                  
                                                                                                                                                                                                                                    
    ticker: Mapped[str] = mapped_column(String(10), primary_key=True)                                                                                                                                                               
    haram_revenue_estimate: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                           
    reasoning: Mapped[Optional[str]] = mapped_column(Text, nullable=True)                                                                                                                                                           
    segments_found: Mapped[Optional[str]] = mapped_column(Text, nullable=True)                                                                                                                                                      
    updated_at: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)                                                                                                                                                    
                                                                                                                                                                                                                                    
class ManualOverride(Base):                                                                                                                                                                                                         
    __tablename__ = "manual_overrides"                                                                                                                                                                                              
                                                                                                                                                                                                                                    
    ticker: Mapped[str] = mapped_column(String(10), primary_key=True)                                                                                                                                                               
    haram_revenue_override: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                           
    debt_ratio_override: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                              
    cash_ratio_override: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                              
    receivables_ratio_override: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                       
    tangibility_ratio_override: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                       
    interest_income_override: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                         
    doubtful_revenue_override: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                        
    reasoning: Mapped[Optional[str]] = mapped_column(Text, nullable=True)                                                                                                                                                           
    is_user_override: Mapped[int] = mapped_column(Integer, default=0)                                                                                                                                                               
    updated_at: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)                                                                                                                                                    
                                                                                                                                                                                                                                    
# Models for processed universe outputs                                                                                                                                                                                             
class UniverseBase:                                                                                                                                                                                                                 
    ticker: Mapped[str] = mapped_column(String(10), primary_key=True)                                                                                                                                                               
    name: Mapped[Optional[str]] = mapped_column(String(255), nullable=True)                                                                                                                                                         
    sector: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)                                                                                                                                                       
    industry: Mapped[Optional[str]] = mapped_column(String(100), nullable=True)                                                                                                                                                     
    total_assets: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                                     
    total_debt: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                                       
    cash_equivalents: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                                 
    accounts_receivable: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                              
    total_revenue: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                                    
    interest_income: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                                  
    shares_outstanding: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                               
    avg_market_cap_36mo: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                              
    raw_info: Mapped[Optional[str]] = mapped_column(Text, nullable=True)                                                                                                                                                            
    sec_filing_url: Mapped[Optional[str]] = mapped_column(Text, nullable=True)                                                                                                                                                      
    fetched_at: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)                                                                                                                                                    
    grade: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)                                                                                                                                                         
    compliance_score: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                                 
    debt_ratio: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                                       
    cash_ratio: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                                       
    tangibility_ratio: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                                
    total_haram_ratio: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                                
    doubtful_ratio: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                                   
    total_combined_ratio: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                             
    purification_per_share: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                           
    halal_failure: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # Specific to halal_rejections                                                                                                                       
                                                                                                                                                                                                                                    
class HalalUniverse(UniverseBase, Base):                                                                                                                                                                                            
    __tablename__ = "halal_universe"                                                                                                                                                                                                
                                                                                                                                                                                                                                    
class DoubtfulUniverse(UniverseBase, Base):                                                                                                                                                                                         
    __tablename__ = "doubtful_universe"                                                                                                                                                                                             
                                                                                                                                                                                                                                    
class HalalRejection(UniverseBase, Base):                                                                                                                                                                                           
    __tablename__ = "halal_rejections"                                                                                                                                                                                              
                                                                                                                                                                                                                                    
class ShariahSegmentMap(Base):                                                                                                                                                                                                      
    __tablename__ = "shariah_segment_map"                                                                                                                                                                                           
    ticker: Mapped[str] = mapped_column(String(10), primary_key=True)                                                                                                                                                               
    segment_name: Mapped[str] = mapped_column(String(255), primary_key=True)                                                                                                                                                        
    compliance_status: Mapped[str] = mapped_column(String(20))  # 'halal', 'haram', 'doubtful'                                                                                                                                      
    notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)                                                                                                                                                               
                                                                                                                                                                                                                                    
class CuratedBenchmark(Base):                                                                                                                                                                                                       
    __tablename__ = "curated_benchmarks"                                                                                                                                                                                            
    ticker: Mapped[str] = mapped_column(String(10), primary_key=True)                                                                                                                                                               
    haram_revenue_override: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                           
    doubtful_revenue_override: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                        
    interest_income_override: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                         
    cash_ratio_override: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                              
    debt_ratio_override: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                              
    tangibility_ratio_override: Mapped[Optional[float]] = mapped_column(Float, nullable=True)                                                                                                                                       
    updated_at: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)                                                                                                                                                    
                                                                                                                                                                                                                                    
class GlobalSegmentPattern(Base):                                                                                                                                                                                                   
    __tablename__ = "global_segment_patterns"                                                                                                                                                                                       
    pattern: Mapped[str] = mapped_column(String(255), primary_key=True)                                                                                                                                                             
    compliance_status: Mapped[str] = mapped_column(String(20))  # 'halal', 'haram', 'doubtful'                                                                                                                                      
    notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)                                                                                                                                                               
                                                                                                                                                                                                                                    
class ProposedSegmentRule(Base):                                                                                                                                                                                                    
    __tablename__ = "proposed_segment_rules"                                                                                                                                                                                        
    ticker: Mapped[str] = mapped_column(String(10), primary_key=True)                                                                                                                                                               
    segment_name: Mapped[str] = mapped_column(String(255), primary_key=True)                                                                                                                                                        
    compliance_status: Mapped[str] = mapped_column(String(20))  # 'halal', 'haram', 'doubtful'                                                                                                                                      
    suggested_notes: Mapped[Optional[str]] = mapped_column(Text, nullable=True)                                                                                                                                                     
    status: Mapped[str] = mapped_column(String(20), default="pending")  # 'pending', 'approved', 'rejected'                                                                                                                         
    created_at: Mapped[Optional[str]] = mapped_column(String(50), nullable=True)                                                                                                                                                    
                                                                                                                                                                                                                                    
class ComplianceScan(Base):                                                                                                                                                                                                         
    __tablename__ = "compliance_scans"                                                                                                                                                                                              
    
    id: Mapped[int] = mapped_column(primary_key=True)
    ticker: Mapped[str] = mapped_column(String(10), index=True)
    compliance_grade: Mapped[ComplianceStatus] = mapped_column(
        Enum(ComplianceStatus, name="compliance_status_enum")
    )
    purification_amount: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    reasoning: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    timestamp: Mapped[datetime.datetime] = mapped_column(default=datetime.datetime.utcnow)

class TradeProposal(Base):
    __tablename__ = "trade_proposals"
    
    id: Mapped[int] = mapped_column(primary_key=True)
    symbol: Mapped[str] = mapped_column(String(10))
    action: Mapped[str] = mapped_column(String(10))  # BUY/SELL
    status: Mapped[str] = mapped_column(String(20), default="PENDING")
    user_id: Mapped[str] = mapped_column(ForeignKey("platform_users.id"))
    
    user: Mapped["User"] = relationship()