import asyncio                                                                                                                                                                                                                                   
from typing import List, Optional                                                                                                                                                                                                                
from fastapi import FastAPI, Depends, HTTPException, BackgroundTasks                                                                                                                                                                             
from fastapi.middleware.cors import CORSMiddleware                                                                                                                                                                                               
from pydantic import BaseModel                                                                                                                                                                                                                   
from sqlalchemy import select                                                                                                                                                                                                                    
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession                                                                                                                                                                             
from sqlalchemy.orm import sessionmaker                                                                                                                                                                                                          
                                                                                                                                                                                                                                                    
from src.db.helpers import ASYNC_DB_URL                                                                                                                                                                                                          
from src.db.models import (                                                                                                                                                                                                                      
    Base,                                                                                                                                                                                                                                        
    HalalUniverse,                                                                                                                                                                                                                               
    DoubtfulUniverse,                                                                                                                                                                                                                            
    HalalRejection,                                                                                                                                                                                                                              
    ManualOverride,                                                                                                                                                                                                                              
    AIOverride,                                                                                                                                                                                                                                  
    ComplianceScan,                                                                                                                                                                                                                              
    TradeProposal,                                                                                                                                                                                                                               
    Stock                                                                                                                                                                                                                                        
)                                                                                                                                                                                                                                                
from src.data.ingestion import run_ingestion                                                                                                                                                                                                     
from src.analysis.screener import run_screener                                                                                                                                                                                                   
from src.analysis.optimizer import run_optimizer                                                                                                                                                                                                 
                                                                                                                                                                                                                                                    
# 1. Initialize FastAPI & enable CORS                                                                                                                                                                                                            
app = FastAPI(title="Shariah Screener API")                                                                                                                                                                                                
                                                                                                                                                                                                                                                    
app.add_middleware(                                                                                                                                                                                                                              
    CORSMiddleware,                                                                                                                                                                                                                              
    allow_origins=["*"],  # Adjust for production if needed                                                                                                                                                                                      
    allow_credentials=True,                                                                                                                                                                                                                      
    allow_methods=["*"],                                                                                                                                                                                                                         
    allow_headers=["*"],                                                                                                                                                                                                                         
)                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    
# 2. Configure Async Database Connections                                                                                                                                                                                                        
engine = create_async_engine(ASYNC_DB_URL)                                                                                                                                                                                                       
AsyncSessionLocal = sessionmaker(                                                                                                                                                                                                                
    engine, class_=AsyncSession, expire_on_commit=False                                                                                                                                                                                          
)                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    
async def get_db_session():                                                                                                                                                                                                                      
    async with AsyncSessionLocal() as session:                                                                                                                                                                                                   
        yield session                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                    
# 3. Define Pydantic Models for Input Validation                                                                                                                                                                                                 
class ManualOverrideInput(BaseModel):                                                                                                                                                                                                            
    ticker: str                                                                                                                                                                                                                                  
    haram_revenue_override: Optional[float] = None                                                                                                                                                                                               
    debt_ratio_override: Optional[float] = None                                                                                                                                                                                                  
    cash_ratio_override: Optional[float] = None                                                                                                                                                                                                  
    receivables_ratio_override: Optional[float] = None                                                                                                                                                                                           
    tangibility_ratio_override: Optional[float] = None                                                                                                                                                                                           
    interest_income_override: Optional[float] = None                                                                                                                                                                                             
    doubtful_revenue_override: Optional[float] = None                                                                                                                                                                                            
    reasoning: Optional[str] = None                                                                                                                                                                                                              
    is_user_override: int = 1                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                    
class AIOverrideInput(BaseModel):                                                                                                                                                                                                                
    ticker: str                                                                                                                                                                                                                                  
    haram_revenue_estimate: Optional[float] = None                                                                                                                                                                                               
    reasoning: Optional[str] = None                                                                                                                                                                                                              
    segments_found: Optional[str] = None                                                                                                                                                                                                         
                                                                                                                                                                                                                                                    
class PortfolioOptimizationInput(BaseModel):                                                                                                                                                                                                     
    max_weight: float = 0.10                                                                                                                                                                                                                     
    sector_cap: float = 0.30                                                                                                                                                                                                                     
    strategy: str = "Max Sharpe"                                                                                                                                                                                                                 
    target_vol: float = 0.15                                                                                                                                                                                                                     
    target_ret: float = 0.15                                                                                                                                                                                                                     
                                                                                                                                                                                                                                                    
class TradeProposalInput(BaseModel):                                                                                                                                                                                                             
    symbol: str                                                                                                                                                                                                                                  
    action: str  # BUY/SELL                                                                                                                                                                                                                      
    user_id: str       
    
    
            
# 4. API Endpoints   
@app.get("/api/universe/halal")                                                                                                                                                                                                                  
async def get_halal_universe(db: AsyncSession = Depends(get_db_session)):                                                                                                                                                                        
    result = await db.execute(select(HalalUniverse))                                                                                                                                                                                             
    return result.scalars().all()                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    
@app.get("/api/universe/doubtful")                                                                                                                                                                                                               
async def get_doubtful_universe(db: AsyncSession = Depends(get_db_session)):                                                                                                                                                                     
    result = await db.execute(select(DoubtfulUniverse))                                                                                                                                                                                          
    return result.scalars().all()                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    
@app.get("/api/universe/rejected")                                                                                                                                                                                                               
async def get_rejected_universe(db: AsyncSession = Depends(get_db_session)):                                                                                                                                                                     
    result = await db.execute(select(HalalRejection))                                                                                                                                                                                            
    return result.scalars().all()                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    
@app.get("/api/overrides/manual")                                                                                                                                                                                                                
async def get_manual_overrides(db: AsyncSession = Depends(get_db_session)):                                                                                                                                                                      
    result = await db.execute(select(ManualOverride))                                                                                                                                                                                            
    return result.scalars().all()                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    
@app.post("/api/overrides/manual")                                                                                                                                                                                                               
async def set_manual_override(data: ManualOverrideInput, db: AsyncSession = Depends(get_db_session)):                                                                                                                                            
    # Merge/upsert manual override record                                                                                                                                                                                                        
    override = ManualOverride(                                                                                                                                                                                                                   
        ticker=data.ticker.upper(),                                                                                                                                                                                                              
        haram_revenue_override=data.haram_revenue_override,                                                                                                                                                                                      
        debt_ratio_override=data.debt_ratio_override,                                                                                                                                                                                            
        cash_ratio_override=data.cash_ratio_override,                                                                                                                                                                                            
        receivables_ratio_override=data.receivables_ratio_override,                                                                                                                                                                              
        tangibility_ratio_override=data.tangibility_ratio_override,                                                                                                                                                                              
        interest_income_override=data.interest_income_override,                                                                                                                                                                                  
        doubtful_revenue_override=data.doubtful_revenue_override,                                                                                                                                                                                
        reasoning=data.reasoning,                                                                                                                                                                                                                
        is_user_override=data.is_user_override,                                                                                                                                                                                                  
        updated_at=None  # Can populate with timestamp if needed                                                                                                                                                                                 
    )                                                                                                                                                                                                                                            
    await db.merge(override)                                                                                                                                                                                                                     
    await db.commit()                                                                                                                                                                                                                            
    # Trigger non-blocking compliance update in the background                                                                                                                                                                                   
    asyncio.create_task(asyncio.to_thread(run_screener))                                                                                                                                                                                         
    return {"status": "success", "message": f"Manual override saved for {data.ticker.upper()}"}                                                                                                                                                  
                                                                                                                                                                                                                                                    
@app.get("/api/overrides/ai")                                                                                                                                                                                                                    
async def get_ai_overrides(db: AsyncSession = Depends(get_db_session)):                                                                                                                                                                          
    result = await db.execute(select(AIOverride))                                                                                                                                                                                                
    return result.scalars().all()                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    
@app.post("/api/overrides/ai")                                                                                                                                                                                                                   
async def set_ai_override(data: AIOverrideInput, db: AsyncSession = Depends(get_db_session)):                                                                                                                                                    
    override = AIOverride(                                                                                                                                                                                                                       
        ticker=data.ticker.upper(),                                                                                                                                                                                                              
        haram_revenue_estimate=data.haram_revenue_estimate,                                                                                                                                                                                      
        reasoning=data.reasoning,                                                                                                                                                                                                                
        segments_found=data.segments_found,                                                                                                                                                                                                      
        updated_at=None                                                                                                                                                                                                                          
    )                                                                                                                                                                                                                                            
    await db.merge(override)                                                                                                                                                                                                                     
    await db.commit()                                                                                                                                                                                                                            
    asyncio.create_task(asyncio.to_thread(run_screener))                                                                                                                                                                                         
    return {"status": "success", "message": f"AI override saved for {data.ticker.upper()}"}                                                                                                                                                      
                                                                                                                                                                                                                                                    
@app.get("/api/compliance/scans")                                                                                                                                                                                                                
async def get_compliance_scans(db: AsyncSession = Depends(get_db_session)):                                                                                                                                                                      
    result = await db.execute(select(ComplianceScan).order_by(ComplianceScan.timestamp.desc()))                                                                                                                                                  
    return result.scalars().all()                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    
@app.get("/api/trade/proposals")                                                                                                                                                                                                                 
async def get_trade_proposals(db: AsyncSession = Depends(get_db_session)):                                                                                                                                                                       
    result = await db.execute(select(TradeProposal))                                                                                                                                                                                             
    return result.scalars().all()                                                                                                                                                                                                                
                                                                                                                                                                                                                                                    
# 5. Background Pipeline Run Handlers                                                                                                                                                                                                            
                                                                                                                                                                                                                                                    
@app.post("/api/pipeline/ingest")
async def trigger_ingestion(background_tasks: BackgroundTasks, refresh: bool = False):
    # Runs the Yahoo Finance ingestion inside the background task queue
    background_tasks.add_task(run_ingestion, refresh=refresh)
    return {"status": "queued", "message": "Yahoo Finance ingestion started in background."}

@app.post("/api/pipeline/screen")
async def trigger_screening(background_tasks: BackgroundTasks, use_current_mcap: bool = False):
    # Runs the AAOIFI compliance screening in background
    background_tasks.add_task(run_screener, use_current_mcap)
    return {"status": "queued", "message": "Compliance screening started in background."}

@app.post("/api/portfolio/optimize")
async def optimize_portfolio(data: PortfolioOptimizationInput):
    # Streamlit/Pandas optimizer is sync-native, execute safely in threadpool
    loop = asyncio.get_running_loop()
    try:
        results = await loop.run_in_executor(
            None,
            lambda: run_optimizer(
                max_weight=data.max_weight,
                sector_cap=data.sector_cap,
                strategy=data.strategy,
                target_vol=data.target_vol,
                target_ret=data.target_ret
            )
        )
        if not results:
            raise HTTPException(status_code=400, detail="Optimization constraints could not be satisfied.")
        return results
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))